from enum import Enum


class RespondState(Enum):
    WAIT_FOR_CREATING = 0
    WAIT_FOR_CREATING_FIO = 1
    WAIT_FOR_CREATING_GENDER = 2
    WAIT_FOR_CREATING_HEIGHT = 3
    WAIT_FOR_CREATING_FACULTY = 4
    WAIT_FOR_CREATING_IMAGE = 5
    WAIT_FOR_FIND = 6
    WAIT_MENU = 7
    DEACTIVATE = 8
    WAIT_PASSWORD = 9
    ADMIN = 10
    WAIT_FOR_ALLOW = 11
    WAIT_CHANGE = 12
